version: "3.8"
services:
    backend-service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:5000"
        volumes:
            # setup file or folder public
            - backend-assets:/app/assets
        network_mode: bridge
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    backend-assets:
        external: false
