GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJuYW1lIjoiQW5kcmVhIiwiZW1haWwiOiJlbWFpbDFAZ21haWwuY29tIiwiaWF0IjoxNjg1MDk3NTAzLCJleHAiOjE2ODUwOTc1MjN9.Bw0yzu8s_ZjKRCc06CFTL_cLCT7_end0WpLs5Rc3OB8
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Andrea",
    "email": "email2@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/articles/

###
POST http://localhost:5000/articles
Content-Type: application/json

{
    "judul": "hahaha3",
    "author": "andrea",
    "content": "blablablabla",
    "image": "bla.png"
}

###
GET http://localhost:5000/articles/5

###
PUT http://localhost:5000/articles/6
Content-Type: application/json

{
    "judul": "kepo luh 2"
}

###
DELETE http://localhost:5000/prices/3

###
GET http://localhost:5000/prices

###
GET http://localhost:5000/prices/3

###
POST http://localhost:5000/prices
Content-Type: application/json

{
    "harga": 11000,
    "provinsi": "NTB"
}

###
PUT http://localhost:5000/prices/1
Content-Type: application/json

{
    "harga": 12000,
    "provinsi": "kalimantan2"
}