name: 🚀 Deploy App...

# Controls when the workflow will run
on: # master = production
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["backend"] # master, development, staging
  pull_request:
    branches: ["backend"] # master, development, staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  app-deploy:
    name: 🚚 BE & FE - CapStone
    runs-on: server-gcp
    steps:
      - name: 🎉 Get latest code
        uses: actions/checkout@v2

      - name: Rename ENV...
        run: |
          mv .env.example .env

      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------

      - name: Manual Replace
        run: |
          sed -i 's#ACCESS_TOKEN_SECRET=#ACCESS_TOKEN_SECRET=${{ secrets.ENV_ACCESS_TOKEN_SECRET }}#g' .env
          sed -i 's#REFRESH_TOKEN_SECRET=#REFRESH_TOKEN_SECRET=${{ secrets.ENV_REFRESH_TOKEN_SECRET }}#g' .env

      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------

      - name: 📡 Docker Compose...
        run: |
          docker-compose pull
          docker-compose up --force-recreate --build -d
          docker image prune -f

      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------

      - name: Dump GitHub context
        if: success() || failure() || cancelled()
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        if: success() || failure() || cancelled()
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        if: success() || failure() || cancelled()
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: success() || failure() || cancelled()
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        if: success() || failure() || cancelled()
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        if: success() || failure() || cancelled()
        run: echo '${{ toJSON(matrix) }}'

      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------